### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by loranger** [Glorian/laravel-elixir-webpack-advanced#6]
Hello,

Could you please add notifications on compilation sucess or failure, please ?
I tried to add some `new elixir.Notification('Webpack Compiled!');`, but was not able...

**Comment by Glorian** [comment]
Hi.

Notifications have been implemented a long time ago:
![image](https://cloud.githubusercontent.com/assets/2189913/15823561/e01b268a-2c03-11e6-92fa-78739705fc34.png)

It works via `webpack-notifier` plugin. 
elixir.Notofocation will not work properly because webpack works natively (without any wrapper like `webpack-stream`) in this package.
